version: '3'
services:
  couchserver:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=guest
      - COUCHDB_PASSWORD=1234
    volumes:
        - ./dbdata:/opt/couchdb/data
  initializer:
    image: curlimages/curl
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - couchserver
    command: ["sh","-c","sleep 15 && curl -u guest:1234 -X PUT couchserver:5984/_users &&  curl -u guest:1234 -X PUT couchserver:5984/test"]